pool:
  vmImage: 'ubuntu-latest'

schedules:
- cron: "0 0 * * *"
  displayName: 每日凌晨更新
  branches:
    include:
    - master
    - releases/*
  always: true
  
trigger:
- master

variables:
  tag: 'aspnet'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'tencentyun'
    command: 'login'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $env:version="$(tag)"
      
      docker pull mcr.microsoft.com/dotnet/core/$env:version
      
      docker tag mcr.microsoft.com/dotnet/core/$env:version ccr.ccs.tencentyun.com/dotnet-core/$env:version
      docker push ccr.ccs.tencentyun.com/dotnet-core/$env:version